[package]
name = "lfff-gui"
version = "1.0.0"
edition = "2024"
description = "GUI frontend for LibreFastbootFirmwareFlasher"
license = "GPL-3.0"

[[bin]]
name = "lfff-gui"
path = "src/main.rs"

[dependencies]
slint = { version = "1.16.1", default-features = false, features = ["std", "compat-1-2", "backend-winit", "renderer-skia", "accessibility"] }
lfff-lib = { path = "../lib" }
rfd = "0.15"
arboard = "3"
dirs = "5"
log = "0.4"
env_logger = "0.11"
libc = "0.2"

[build-dependencies]
slint-build = "1.16.1"
