[package]
name = "lfff-lib"
version = "2.0.5"
edition = "2024"
description = "Core library for LibreFastbootFirmwareFlasher"
license = "GPL-3.0"
repository = "https://github.com/mrFrok/LibreFastbootFirmwareFlasher"

[lib]
name = "lfff_lib"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
log = "0.4"
sha2 = "0.10"
digest = "0.10"
regex = "1"
which = "8"
zip = { version = "2", default-features = false, features = ["deflate"] }
url = "2"
colored = "3"

[dev-dependencies]
tempfile = "3"
